// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL="https://hknxtpyiiirujgulvaiw.supabase.co"
const SUPABASE_PUBLISHABLE_KEY="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imhrbnh0cHlpaWlydWpndWx2YWl3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE1MzgyMTYsImV4cCI6MjA2NzExNDIxNn0.Mchha6M81dKFm5jxiV2QWLIF9aVq0UEBD1BqaxpSego"

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);