// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gnwwppdxqmnnltalvadz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdud3dwcGR4cW1ubmx0YWx2YWR6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk3MjIyMzgsImV4cCI6MjA2NTI5ODIzOH0.Jyl34U2XTiiQ5sOfzl6IFZ0sMzlCEEc-dmfgu8Xhthw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);